package com.zhouzhi.emeraldcraft.init;

import com.zhouzhi.emeraldcraft.EmeraldCraft;
import com.zhouzhi.emeraldcraft.item.EmeraldUpgradeCore;
import com.zhouzhi.emeraldcraft.item.genesis_emerald.GenesisEmeraldItem;
import com.zhouzhi.emeraldcraft.item.genesis_emerald.GenesisEmeraldSwordItem;
import com.zhouzhi.emeraldcraft.item.inferno_emerald.InfernoEmeraldItem;
import com.zhouzhi.emeraldcraft.item.inferno_emerald.InfernoEmeraldSwordItem;
import com.zhouzhi.emeraldcraft.item.lava_emerald.*;
import com.zhouzhi.emeraldcraft.item.oblivion_emerald.OblivionEmeraldItem;
import com.zhouzhi.emeraldcraft.item.oblivion_emerald.OblivionEmeraldSwordItem;
import com.zhouzhi.emeraldcraft.item.remined_emerald.*;
import com.zhouzhi.emeraldcraft.item.void_emerald.*;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(EmeraldCraft.MOD_ID);
	public static final DeferredItem<Item> REFINED_EMERALD;
    public static final DeferredItem<Item> REFINED_EMERALD_T_2;
    public static final DeferredItem<Item> REFINED_EMERALD_T_3;
	public static final DeferredItem<Item> VOID_EMERALD;
	public static final DeferredItem<Item> LAVA_EMERALD;
	public static final DeferredItem<Item> LAVA_EMERALD_T2;
	public static final DeferredItem<Item> REFINED_EMERALD_PLUS;
	public static final DeferredItem<Item> EMERALD_UPGRADE_CORE;
	public static final DeferredItem<Item> GENESIS_EMERALD;
	public static final DeferredItem<Item> INFERNO_EMERALD;
	public static final DeferredItem<Item> OBLIVION_EMERALD;
	public static final DeferredItem<Item> REFINED_EMERALD_BLOCK;
	public static final DeferredItem<Item> REFINED_EMERALD_BLOCK_2;
    public static final DeferredItem<Item> REFINED_EMERALD_BLOCK_3;
	public static final DeferredItem<Item> EMERALD_SWORD;
    public static final DeferredItem<Item> EMERALD_SWORD_T_2;
    public static final DeferredItem<Item> EMERALD_SWORD_T_3;
    public static final DeferredItem<Item> SKYFILLING_BLADE;
    public static final DeferredItem<Item> IRON_SWORD_INLAID_WITH_REFINED_EMERALD;
    public static final DeferredItem<Item> IRON_SWORD_INLAID_WITH_REFINED_EMERALD_T2;
    public static final DeferredItem<Item> VOID_EMERALD_SWORD;
	public static final DeferredItem<Item> LAVA_EMERALD_SWORD;
	public static final DeferredItem<Item> GENESIS_EMERALD_SWORD;
	public static final DeferredItem<Item> INFERNO_EMERALD_SWORD;
	public static final DeferredItem<Item> OBLIVION_EMERALD_SWORD;
    public static final DeferredItem<Item> EMERALD_AXE;
	public static final DeferredItem<Item> EMERALD_AXE_T_2;
    public static final DeferredItem<Item> EMERALD_AXE_T_3;
    public static final DeferredItem<Item> IRON_AXE_INLAID_WITH_REFINED_EMERALD;
    public static final DeferredItem<Item> IRON_AXE_INLAID_WITH_REFINED_EMERALD_T2;
	public static final DeferredItem<Item> VOID_EMERALD_AXE;
	public static final DeferredItem<Item> LAVA_EMERALD_AXE;
	//public static final DeferredItem<Item> GENESIS_EMERALD_AXE;
	//public static final DeferredItem<Item> INFERNO_EMERALD_AXE;
	//public static final DeferredItem<Item> OBLIVION_EMERALD_AXE;
    public static final DeferredItem<Item> EMERALD_PICKAXE;
    public static final DeferredItem<Item> EMERALD_PICKAXE_T_2;
	public static final DeferredItem<Item> EMERALD_PICKAXE_T_3;
    public static final DeferredItem<Item> IRON_PICKAXE_INLAID_WITH_REFINED_EMERALD;
    public static final DeferredItem<Item> IRON_PICKAXE_INLAID_WITH_REFINED_EMERALD_T2;
	public static final DeferredItem<Item> VOID_EMERALD_PICKAXE;
	public static final DeferredItem<Item> LAVA_EMERALD_PICKAXE;
	//public static final DeferredItem<Item> GENESIS_EMERALD_PICKAXE;
	//public static final DeferredItem<Item> INFERNO_EMERALD_PICKAXE;
	//public static final DeferredItem<Item> OBLIVION_EMERALD_PICKAXE;
	public static final DeferredItem<Item> EMERALD_SHOVEL;
	public static final DeferredItem<Item> EMERALD_SHOVEL_T_2;
	public static final DeferredItem<Item> EMERALD_SHOVEL_T_3;
    public static final DeferredItem<Item> IRON_SHOVEL_INLAID_WITH_REFINED_EMERALD;
    public static final DeferredItem<Item> IRON_SHOVEL_INLAID_WITH_REFINED_EMERALD_T2;
    public static final DeferredItem<Item> VOID_EMERALD_SHOVEL;
	public static final DeferredItem<Item> LAVA_EMERALD_SHOVEL;
	//public static final DeferredItem<Item> GENESIS_EMERALD_SHOVEL;
	//public static final DeferredItem<Item> INFERNO_EMERALD_SHOVEL;
	//public static final DeferredItem<Item> OBLIVION_EMERALD_SHOVEL;
	public static final DeferredItem<Item> EMERALD_HOE;
	public static final DeferredItem<Item> EMERALD_HOE_T_2;
	public static final DeferredItem<Item> EMERALD_HOE_T_3;
    public static final DeferredItem<Item> IRON_HOE_INLAID_WITH_REFINED_EMERALD;
    public static final DeferredItem<Item> IRON_HOE_INLAID_WITH_REFINED_EMERALD_T2;
	public static final DeferredItem<Item> VOID_EMERALD_HOE;
	public static final DeferredItem<Item> LAVA_EMERALD_HOE;
	//public static final DeferredItem<Item> GENESIS_EMERALD_HOE;
	//public static final DeferredItem<Item> INFERNO_EMERALD_HOE;
	//public static final DeferredItem<Item> OBLIVION_EMERALD_HOE;
	public static final DeferredItem<Item> EMERALD_ARMOR_HELMET;
	public static final DeferredItem<Item> EMERALD_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EMERALD_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> EMERALD_ARMOR_BOOTS;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_2_HELMET;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_2_CHESTPLATE;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_2_LEGGINGS;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_2_BOOTS;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_3_HELMET;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_3_CHESTPLATE;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_3_LEGGINGS;
	public static final DeferredItem<Item> EMERALD_ARMOR_T_3_BOOTS;
	public static final DeferredItem<Item> VOID_EMERALD_ARMOR_HELMET;
	public static final DeferredItem<Item> VOID_EMERALD_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> VOID_EMERALD_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> VOID_EMERALD_ARMOR_BOOTS;
	public static final DeferredItem<Item> VOID_EMERALD_SHIELD;
	public static final DeferredItem<Item> LAVA_EMERALD_SWORD_T2;
	public static final DeferredItem<Item> LAVA_EMERALD_AXE_T2;
	public static final DeferredItem<Item> LAVA_EMERALD_PICKAXE_T2;
	public static final DeferredItem<Item> LAVA_EMERALD_SHOVEL_T2;
	public static final DeferredItem<Item> LAVA_EMERALD_HOE_T2;
	static {
		REFINED_EMERALD = REGISTRY.register("refined_emerald", RefinedEmeraldItem::new);
		REFINED_EMERALD_BLOCK = block(ModBlocks.REFINED_EMERALD_BLOCK, new Item.Properties().rarity(Rarity.RARE));
		EMERALD_PICKAXE = REGISTRY.register("emerald_pickaxe", EmeraldPickaxeItem::new);
		REFINED_EMERALD_BLOCK_2 = block(ModBlocks.REFINED_EMERALD_BLOCK_2, new Item.Properties().rarity(Rarity.RARE));
		REFINED_EMERALD_T_2 = REGISTRY.register("refined_emerald_t_2", RefinedEmeraldT2Item::new);
		EMERALD_PICKAXE_T_2 = REGISTRY.register("emerald_pickaxe_t_2", EmeraldPickaxeT2Item::new);
		EMERALD_SWORD = REGISTRY.register("emerald_sword", EmeraldSwordItem::new);
		EMERALD_AXE = REGISTRY.register("emerald_axe", EmeraldAxeItem::new);
		EMERALD_SWORD_T_2 = REGISTRY.register("emerald_sword_t_2", EmeraldSwordT2Item::new);
		EMERALD_AXE_T_2 = REGISTRY.register("emerald_axe_t_2", EmeraldAxeT2Item::new);
		REFINED_EMERALD_T_3 = REGISTRY.register("refined_emerald_t_3", RefinedEmeraldT3Item::new);
		REFINED_EMERALD_BLOCK_3 = block(ModBlocks.REFINED_EMERALD_BLOCK_3, new Item.Properties().rarity(Rarity.EPIC).fireResistant());
		EMERALD_SWORD_T_3 = REGISTRY.register("emerald_sword_t_3", EmeraldSwordT3Item::new);
		EMERALD_AXE_T_3 = REGISTRY.register("emerald_axe_t_3", EmeraldAxeT3Item::new);
		EMERALD_PICKAXE_T_3 = REGISTRY.register("emerald_pickaxe_t_3", EmeraldPickaxeT3Item::new);
		EMERALD_SHOVEL = REGISTRY.register("emerald_shovel", EmeraldShovelItem::new);
		EMERALD_SHOVEL_T_2 = REGISTRY.register("emerald_shovel_t_2", EmeraldShovelT2Item::new);
		EMERALD_SHOVEL_T_3 = REGISTRY.register("emerald_shovel_t_3", EmeraldShovelT3Item::new);
		EMERALD_HOE = REGISTRY.register("emerald_hoe", EmeraldHoeItem::new);
		EMERALD_HOE_T_2 = REGISTRY.register("emerald_hoe_t_2", EmeraldHoeT2Item::new);
		EMERALD_HOE_T_3 = REGISTRY.register("emerald_hoe_t_3", EmeraldHoeT3Item::new);
		EMERALD_ARMOR_HELMET = REGISTRY.register("emerald_armor_helmet", EmeraldArmorItem.Helmet::new);
		EMERALD_ARMOR_CHESTPLATE = REGISTRY.register("emerald_armor_chestplate", EmeraldArmorItem.Chestplate::new);
		EMERALD_ARMOR_LEGGINGS = REGISTRY.register("emerald_armor_leggings", EmeraldArmorItem.Leggings::new);
		EMERALD_ARMOR_BOOTS = REGISTRY.register("emerald_armor_boots", EmeraldArmorItem.Boots::new);
		EMERALD_ARMOR_T_2_HELMET = REGISTRY.register("emerald_armor_t_2_helmet", EmeraldArmorT2Item.Helmet::new);
		EMERALD_ARMOR_T_2_CHESTPLATE = REGISTRY.register("emerald_armor_t_2_chestplate", EmeraldArmorT2Item.Chestplate::new);
		EMERALD_ARMOR_T_2_LEGGINGS = REGISTRY.register("emerald_armor_t_2_leggings", EmeraldArmorT2Item.Leggings::new);
		EMERALD_ARMOR_T_2_BOOTS = REGISTRY.register("emerald_armor_t_2_boots", EmeraldArmorT2Item.Boots::new);
		EMERALD_ARMOR_T_3_HELMET = REGISTRY.register("emerald_armor_t_3_helmet", EmeraldArmorT3Item.Helmet::new);
		EMERALD_ARMOR_T_3_CHESTPLATE = REGISTRY.register("emerald_armor_t_3_chestplate", EmeraldArmorT3Item.Chestplate::new);
		EMERALD_ARMOR_T_3_LEGGINGS = REGISTRY.register("emerald_armor_t_3_leggings", EmeraldArmorT3Item.Leggings::new);
		EMERALD_ARMOR_T_3_BOOTS = REGISTRY.register("emerald_armor_t_3_boots", EmeraldArmorT3Item.Boots::new);
		VOID_EMERALD_ARMOR_HELMET = REGISTRY.register("void_emerald_helmet", VoidEmeraldArmorItem.Helmet::new);
		VOID_EMERALD_ARMOR_CHESTPLATE = REGISTRY.register("void_emerald_chestplate", VoidEmeraldArmorItem.Chestplate::new);
		VOID_EMERALD_ARMOR_LEGGINGS = REGISTRY.register("void_emerald_leggings", VoidEmeraldArmorItem.Leggings::new);
		VOID_EMERALD_ARMOR_BOOTS = REGISTRY.register("void_emerald_boots", VoidEmeraldArmorItem.Boots::new);
		REFINED_EMERALD_PLUS = REGISTRY.register("refined_emerald_plus", RefinedEmeraldPlusItem::new);
		SKYFILLING_BLADE = REGISTRY.register("sky_filling_blade", SkyFillingBladeItem::new);
        IRON_SWORD_INLAID_WITH_REFINED_EMERALD = REGISTRY.register("iron_sword_with_refined_emerald", IronSwordInlaidWithRefinedEmeraldItem::new);
        IRON_SWORD_INLAID_WITH_REFINED_EMERALD_T2 = REGISTRY.register("iron_sword_with_refined_emerald_t2", IronSwordInlaidWithRefinedEmeraldT2Item::new);
        IRON_AXE_INLAID_WITH_REFINED_EMERALD = REGISTRY.register("iron_axe_with_refined_emerald", IronAxeInlaidWithRefinedEmeraldItem::new);
        IRON_AXE_INLAID_WITH_REFINED_EMERALD_T2 = REGISTRY.register("iron_axe_with_refined_emerald_t2", IronAxeInlaidWithRefinedEmeraldItemT2::new);
        IRON_PICKAXE_INLAID_WITH_REFINED_EMERALD = REGISTRY.register("iron_pickaxe_with_refined_emerald", IronPickaxeInlaidWithRefinedEmeraldItem::new);
        IRON_PICKAXE_INLAID_WITH_REFINED_EMERALD_T2 = REGISTRY.register("iron_pickaxe_with_refined_emerald_t2", IronPickaxeInlaidWithRefinedEmeraldItemT2::new);
        IRON_SHOVEL_INLAID_WITH_REFINED_EMERALD = REGISTRY.register("iron_shovel_with_refined_emerald", IronShovelInlaidWithRefinedEmeraldItem::new);
        IRON_SHOVEL_INLAID_WITH_REFINED_EMERALD_T2 = REGISTRY.register("iron_shovel_with_refined_emerald_t2", IronShovelInlaidWithRefinedEmeraldItemT2::new);
        IRON_HOE_INLAID_WITH_REFINED_EMERALD = REGISTRY.register("iron_hoe_with_refined_emerald", IronHoeInlaidWithRefinedEmeraldItem::new);
        IRON_HOE_INLAID_WITH_REFINED_EMERALD_T2 = REGISTRY.register("iron_hoe_with_refined_emerald_t2", IronHoeInlaidWithRefinedEmeraldItemT2::new);
        VOID_EMERALD = REGISTRY.register("void_emerald", VoidEmeraldItem::new);
        VOID_EMERALD_SWORD = REGISTRY.register("void_emerald_sword", VoidEmeraldSwordItem::new);
        VOID_EMERALD_AXE = REGISTRY.register("void_emerald_axe", VoidEmeraldAxeItem::new);
        VOID_EMERALD_PICKAXE = REGISTRY.register("void_emerald_pickaxe", VoidEmeraldPickaxeItem::new);
        VOID_EMERALD_SHOVEL = REGISTRY.register("void_emerald_shovel", VoidEmeraldShovelItem::new);
        VOID_EMERALD_HOE = REGISTRY.register("void_emerald_hoe", VoidEmeraldHoeItem::new);
		VOID_EMERALD_SHIELD = REGISTRY.register("void_emerald_shield", VoidEmeraldShieldItem::new);
		LAVA_EMERALD = REGISTRY.register("lava_emerald", LavaEmeraldItem::new);
		LAVA_EMERALD_SWORD = REGISTRY.register("lava_emerald_sword", LavaEmeraldSwordItem::new);
		LAVA_EMERALD_AXE = REGISTRY.register("lava_emerald_axe", LavaEmeraldAxeItem::new);
		LAVA_EMERALD_PICKAXE = REGISTRY.register("lava_emerald_pickaxe", LavaEmeraldPickaxeItem::new);
		LAVA_EMERALD_SHOVEL = REGISTRY.register("lava_emerald_shovel", LavaEmeraldShovelItem::new);
		LAVA_EMERALD_HOE = REGISTRY.register("lava_emerald_hoe", LavaEmeraldHoeItem::new);
		LAVA_EMERALD_T2 = REGISTRY.register("lava_emerald_t2", LavaEmeraldT2Item::new);
		LAVA_EMERALD_SWORD_T2 = REGISTRY.register("lava_emerald_sword_t2", LavaEmeraldSwordT2Item::new);
		LAVA_EMERALD_AXE_T2 = REGISTRY.register("lava_emerald_axe_t2", LavaEmeraldAxeT2Item::new);
		LAVA_EMERALD_PICKAXE_T2 = REGISTRY.register("lava_emerald_pickaxe_t2", LavaEmeraldPickaxeT2Item::new);
		LAVA_EMERALD_SHOVEL_T2 = REGISTRY.register("lava_emerald_shovel_t2", LavaEmeraldShovelT2Item::new);
		LAVA_EMERALD_HOE_T2 = REGISTRY.register("lava_emerald_hoe_t2", LavaEmeraldHoeT2Item::new);
		EMERALD_UPGRADE_CORE = REGISTRY.register("emerald_upgrade_core", EmeraldUpgradeCore::new);
		GENESIS_EMERALD = REGISTRY.register("genesis_emerald", GenesisEmeraldItem::new);
		GENESIS_EMERALD_SWORD = REGISTRY.register("genesis_emerald_sword", GenesisEmeraldSwordItem::new);
        INFERNO_EMERALD = REGISTRY.register("inferno_emerald", InfernoEmeraldItem::new);
		INFERNO_EMERALD_SWORD = REGISTRY.register("inferno_emerald_sword", InfernoEmeraldSwordItem::new);
        OBLIVION_EMERALD = REGISTRY.register("oblivion_emerald", OblivionEmeraldItem::new);
		OBLIVION_EMERALD_SWORD = REGISTRY.register("oblivion_emerald_sword", OblivionEmeraldSwordItem::new);
	}
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}